services:
  nextjs-app:
    container_name: vault
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    volumes:
      - .:/my_app
      - /my_app/node_modules
